### PR TITLE
Populate template with auto_assign always.

### LINKED ISSUE #15: Auto-populate template arguments is broken in subclasses
https://github.com/level12/keg/blob/master/keg/web.py#L155 can be moved out of the `if` so that it `auto_populate` will always run.

### PR DESCRIPTION
**Pull request by nZac**
Fixes #15.

### CODE REVIEW

**Comment by rsyring** [comment]
The change will break the auto-assign functionality...I apparently don't have any tests covering that.  :(

**Comment by rsyring** [comment]
I've added some tests on master for auto-assign functionality.  Currently, I don't think it makes sense to process the auto-assign if a response was passed back.  Reason: if you have a response already, that response is what will be served to the client.  Even if you processed the auto-assign variables, the response is already there, so a template will never again get rendered.

What was the specific problem you were having?  I'm wondering if we can address it another way.

**Comment by nZac** [comment]
> Even if you processed the auto-assign variables, the response is already there, so a template will never again get rendered.

That is why I placed the call where I did. `process_auto_assign` merely loops a tuple and adds the items to the `template_args` `dict`. I am not sure what happens to that `dict` after that but in my tests those values get included in the template. I am guessing that happens at a latter stage in the execution.

Long story short, this PR suggests that one of the things we do prior to asking the view function for a response is preload the variables in `auto_assign` into the `template_args`. If you don't want a particular variable in a particular response you can `.pop` it out or override in the view function.

**Comment by rsyring** [comment]
Rebase on my changes to master and you should see failures.  The point is that auto-assign applys after the primary responding method is called.  So that any attributes set on the view instance while the responding view is responding are also sent to the template.  But if the responding view returns a response, it becomes pointless.  

Going to close this b/c I'm sure moving the function to the top isn't the answer.  Let's revisit the real need for FIS and see what we come up with.

**Pull request closed without merging**
